export const SECTIONS = {
    MY_PROFILE: 'MY_PROFILE',
    MY_APPOINTMENTS: 'MY_APPOINTMENTS',
    PENDING_APPOINTMENTS: 'PENDING_APPOINTMENTS',
}

export const SECTIONS_TITLE={
    MY_PROFILE_TITLE: 'MI PERFIL',
    MY_APPOINTMENTS_TITLE: 'MIS TURNOS',
    PENDING_APPOINTMENTS_TITLE: 'MIS TURNOS PENDIENTES'

}